name: Build and Publish Python Package

on:
  push:
    branches: [main]
    tags: ["*"]
  workflow_dispatch:

permissions:
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (version from .python-version file)
        uses: actions/setup-python@v5

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Determine version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            VERSION="dev-$(date +'%Y%m%d%H%M%S')"
          else
            VERSION="dev-pr-$(date +'%Y%m%d%H%M%S')"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Package version: $VERSION"

      - name: Update version in pyproject.toml
        run: |
          # Replace the version in pyproject.toml
          sed -i "s/version = \"0.0.0\"/version = \"$VERSION\"/" pyproject.toml
          cat pyproject.toml | grep version

      - name: Build package
        run: uv build

      - name: Publish to PyPi
        run: uv publish -v dist/*
